### PR TITLE
Geolocate User, and Persist Zip to URL

### PR DESCRIPTION
**Pull request by jlev**
For #24 and #20

### CODE REVIEW

**Comment by jlev** [comment]
switched base to staging to reflect new process. will file separate PRs per issue ticket in the future...

**Comment by jasonkalmeida** [comment]
Regarding #24 - @mick will this come into conflict with your current viewport/region scope implementation?

**Comment by mick** [comment]
re #24 We should pick either zipcode in the url or center of the map in the url.  keeping the center of map allows for panning around and then sharing that current view.  We could make zipcode an optional param to initially center the map.

re [geolocation](https://github.com/techforwarren/eventmap/pull/30/files#diff-d7175f37aeb287eb156b0b0097798fe6R19) we won't need to reverse geocode anything.  Just center the map.

**Comment by jlev** [comment]
Ok, it looks like Mick's Mapbox GL branch is the direction we're going (assuming we've resolved outstanding issues in #25).

I'll close this and open a new PR with the geolocation functionality in a button (along with zoom in/out, which right now is hidden). Can also pop that on load for mobile devices, if that's desired in situations where we don't already have a viewport set in the URL.

**Pull request closed without merging**
